### ISSUE TITLE
vue-chartjs v3.2.x build error

### ISSUE THREAD

**Issue by 0PEIN0** [kaleguy/leovue#1]
Since in package.json has the `vue-chartjs` package `^3.0.0` declared version and their `v3.2.x` build raised an error, got this error in browser console after building leovue: https://github.com/apertureless/vue-chartjs/issues/310 

Used `v3.1.0` explicitly in package json to fix the problem. Maybe using it would be safe bet to not let them to crash the build of leovue?

**Comment by apertureless** [comment]
It's fixed now with `vue-chartjs@3.2.1`

**Comment by 0PEIN0** [comment]
@apertureless Awesome. Thanks.

**Comment by 0PEIN0** [comment]
@kaleguy Closing this issue as its no longer valid.
