### ISSUE TITLE
leo node with jinja template is not displayed 

### ISSUE THREAD

**Issue by xu4wang** [kaleguy/leovue#11]
In my leo file, there are some node with the format of Jinja template, for example, it includes some text as below:

`      token {{ decrypt("gAAAAABdhei7v18G8cwZcLBVfOwmJDAvYVWvoxQlAX03gxdoGU6Kp9CE8O7Ki0N8iYpvWtVeLu__5-KlxYKwDhgKLo1aSiYDrw==" ,"wmGj7cOGAHS1q8L0N2F3Ig==")}}
      `

When I tried to display those nodes, the body panel is empty.

**Comment by kaleguy** [comment]
This is because LeoVue by default tries to parse the node body as a Vue template. So it is trying to eval the {{. I'll add a directive to turn this off.

**Comment by kaleguy** [comment]
Added a "@nocompile" directive to turn off Vue compilation per node. Add this to the text of any node which has "{{ example }}".
