### ISSUE TITLE
Is it worth the effort to run locally (w/o local server)?

### ISSUE THREAD

**Issue by drmikecrowe** [kaleguy/leovue#3]
I was hoping to run this locally (I have a .leo file I'd love to distribute privately, can't really host it publicly).

I started looking at expanding how the .leo file is read.   The following *non-working* code is food for thought:

```javascript

function loadLocalFile(filename) {
  var p = new Promise((resolve, reject) => {
    if (!filename) {
      reject("File not found")
    }
    var reader = new FileReader()
    reader.onload = function(e) {
      var contents = e.target.result
      resolve(contents)
    };
    reader.readAsDataURL(filename);
  })
}

function loadDoc (filename) {
  console.log('loading file:', filename, window.lconfig, 'test')

  var p = new Promise((resolve, reject) => {
    if (window.location.origin === "file://") {
      return loadLocalFile(filename)
    }
    axios.get(filename)
      .then(function (response) {
        resolve(response.data)
      })
      .catch(function (error) {
        console.log(error)
        reject()
      })
  })
  return p
}
```

However, in order to continue, I *think* this would work:

* Add a hidden <input type="file"> tag with events
* Populate the file with the filename 
* File loads   (?)

But, I'm not absolutely positive the second step will work.  I think it might violate javascript security and be blocked.

Any thoughts on this?  Have you tried this already and know it won't work?

Currently, this code errors out with:  
`TypeError: Failed to execute 'readAsDataURL' on 'FileReader': parameter 1 is not of type 'Blob'`

**Comment by kaleguy** [comment]
There is no way to run without a server. Vue won't work without one. However, you can install http-server (npm install -g http-server) and run with that.
