### ISSUE TITLE
Make this the next generation of Leo

### ISSUE THREAD

**Issue by shakfu** [kaleguy/leovue#4]
Well done, this is awesome! 

Ok, I've known and used Leo since its pre-python days! I've always thought that it needs to be pushed to the web somehow, and I believe you are half of the way there! If only Edward could decouple the leo engine from its gui UI, you could plug it into your system and have a persistent editor via the web, with all the beautiful possibilities that that entails. 👍 

S

**Comment by kaleguy** [comment]
Glad you're enjoying the program. Leo and Leo Vue have somewhat different aims (LV is focused on presentation and has features that wouldn't make sense in Leo), but I am working towards getting at least the ability to make and edit outlines part of Leo Vue. Probably this will be done via integration with form.io. I will be working on that next after finishing the web scraping feature (works with the scraper-api project).

**Comment by shakfu** [comment]
Really glad to hear that you're considering editing functionality. When I first played with your online demo of leavue, I was thinking about how you could switch from an editor view (like leo-editor itself) to your presentation view via something like https://codemirror.net 

Good luck though. Exciting project indeed!

**Comment by kaleguy** [comment]
Yes, will make an editor view. It won't be a replacement for the Leo
desktop program though. The idea is to make an online app that people can
use to collaborate to build content trees, so I'm not planning on
implementing the file features, although people will be able to export to
Leo desktop.

Joe
