### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by meahmadi** [kaleguy/leovue#6]
Hi,
There Are many languages like arabic/farsi/hebrew which are "right to left". fortunately Html Support for RTL languages is very straight forward, Would You PLEASE support RTL Languages.

**Comment by kaleguy** [comment]
Hi,

Create a sample Leo file with RTL content and create a pull request to https://github.com/kaleguy/leo-examples and I'll take a look. Also create a screenshot of how you want it to look, e.g. should tree menu be on left side etc.

Joe
