### ISSUE TITLE
@clean @auto node makes no outline displayed on left side

### ISSUE THREAD

**Issue by xu4wang** [kaleguy/leovue#9]
In case the leo file is with @clean or @auto node, the outlines are not displayed on left side. If switch to Graphic Tree, can still browse the data.

**Comment by xu4wang** [comment]
[docs.leo.txt](https://github.com/kaleguy/leovue/files/3586450/docs.leo.txt)

Attached is a simple leo file with only two onlines to reproduce the issue.

**Comment by xu4wang** [comment]
I think the reason is sometimes for @auto node, leo does not store the body into .leo file, and leoVUE was trying to access that.

**Comment by kaleguy** [comment]
LeoVue doesn't support @auto nodes.

**Comment by xu4wang** [comment]
OK Noted. I will workaround this.
